### PR TITLE
Add support for output in PAF (Pairwise mApping Format)

### PR DESCRIPTION
**Pull request by urbanslug**
It would be nice if lastz could output alignments in [PAF](https://github.com/lh3/miniasm/blob/master/PAF.md).

### CODE REVIEW

**Comment by rsharris** [comment]
Thanks,  urbanslug, I will take a look at that.

I haven't looked at your implementation yet. Looking at the PAF format spec, it looks like all those fields, except one (mapping quality), are currently supported by --format=general. This suggests that the implementation could be as simple as adding a pre-canned fields string, as was done for --format=blastn, and add support for mapping quality.

Anyway, I will take a look at your implementation, though I can't make any promises as to how soon.

**Comment by urbanslug** [comment]
It's okay. I'll take a closer look at `--format=general` and see if I can improve this PR.

**Comment by rsharris** [comment]
I was just thinking of how I would implement it.

I've looked *some* at your implementation — it looks pretty thorough. I note that mapping quality is not actually computed, it's just set to the 'undefined' state of 255. Which is probably reasonable in the context of lastz. To do more, IIRC, one has to involve information beyond the scope of that single alignment (I'd have to read the minimap paper to see the details).

I presume the desire to have this supported inside lastz is because there are downstream tools that process PAF. Toward that end, another solution would be a simple awk, perl, or python oneliner that would take lastz's --format=general output (with the appropriate fields) and append 255 for the mapping quality.

**Comment by urbanslug** [comment]
Yes about the mapping quality and the reason to have this supported in lastz.

Given your thoughts on general. 
As an initial implementation, I could have the option to output PAF call a customized version of `print_genpaf_job_header` so that it complies with the PAF spec. What do you think?

**Comment by rsharris** [comment]
--format=general-:xxxxxx (with a hyphen after general) suppresses the header line. PAF has no header line, right?

Looking at the list of fields for --format=general, it doesn't look like it has a field corresponding directly to PAF column 11 (alignment block length). This could be computed by adding up the fields nmatch, nmismatch, and cgap.

So I think --format=general-:name2,size2,zstart2+,zend2+,strand2,name1,size1,zstart1,zend1,nmatch, nmismatch,cgap fed into a script that replaced column 11 with the sum of c10+c11+c12 and then replaced c12 with 255 would be compliant PAF.

I usually do that sort of thing in awk, e.g. pipe the lastz output into awk '{ $11=$10+$11+$12; $12=255; print $0; }'

I'm not suggesting that's the best solution. I'm trying to gauge whether that would be adequate for your need.

**Comment by ekg** [comment]
The cigar needs to be in a custom flag field starting with cg:Z:...

This is an unfortunate feature of PAF. The cigar is not essential, so it doesn't sit in a fixed field position. However, we often require it and it's expected in such a flag field. This would seem to make the generic format difficult to use.

**Comment by rsharris** [comment]
I built and ran your code, and compared the output (on a small contrived example) to the piped command below.

I now see that you are adding some additional tags that are optional in paf. So in my piped script I've added the fields for those.

Differences I encountered, between your implementation and my piped script:

(1) You are adding 1 to the sequence lengths. I see in the code that that is intentional, but I do not understand why. This would seem to be non-compliant with the PAF spec. Does minimap report the sequence length as 1 longer than it actually is?

(2) column 2 is different whenever the alignment is on the reverse strand. I couldn't figure out why.

(3) column 11 is different. It looks like you have not included the number of mismatches.

(4) the cigar tag is different -- yours includes a "1" when the run length is 1, whereas mine leaves that out. They are probably otherwise the same. It's not at all clear to me whether mine is correct in this context. CIGAR predates SAM, and I've seen many different interpretations. I don't see anything in the SAM spec that addresses run lengths. I *do* see an example in the spec that has a "1D" which suggests they may require run lengths even if they have length 1.

```
    lastz apple.fa orange.fa
        --format=general-:name2,size2,zstart2+,end2+,strand2,name1,size1,zstart1,end1,nmatch,nmismatch,cgap,score,cigarx
      | awk '{
             $11 = $10+$11+$12;
             $12 = 255;
             $13 = "as:i:"$13;
             $14 = "cg:Z:"$14;
             print $0;
             }'
```

**Comment by rsharris** [comment]
@ekg I now see that urbanslug's implementation does include the cigar tag.

This makes me think the solution using --format=general and awk is a preferred solution, because what additional tags someone expects to have in her PAF could differ from user to user.

The issue is then where would be the best place to document that solution (once we resolve the details). I could certainly add it at the end of the readme, in the "advanced topics" section, with a pointer to that from the "other output" section.

**Comment by rsharris** [comment]
@ekg @urbanslug Are you familiar enough with downstream tools that accept PAF to know whether they will handle single-base CIGAR operators that leave out the run length?

**Comment by ekg** [comment]
For downstream use we will need the cigar string in the given format. That is, 1= rather than just = is required.

PAF is an increasingly-used alignment output format for these kinds of alignments. I appreciate the awk based solution can provide the same results. But, we are also interested in embedding lastz in another context. It would be nice not to fork the codebase in doing so. That's why we are interested in integrating PAF output this way. It will also prevent confusion for users in the future, at the admitted cost of more code in the repo.

**Comment by rsharris** [comment]
OK. My preference then would be to add this with my own implementation, internally based on the generic tab-delimited format. I believe this will be easier to maintain going forward. It involves adding four new generic fields, all of which will be simple to implement using functions that already exist. (Similar to the implementation of blastn format, I would not expose these fields directly to the user).

There are a couple issues that need to be resolved before I implement that.

(1) The code in the pull request reports the sequence length as one longer than the number of bases in the sequence. Is this correct? The code has a comment that suggests this is to account for a trailing NUL terminator in the string. But I don't see that mentioned in the PAF spec.  Does minimap really report sequence lengths as the string length including the terminator?

(2) Column 11 differs between the pull request and the awk-script version. I believe the is the result of the pull request not counting mismatches. Can you verify this?

(3) Column 2 differs between the pull request and the awk-script version, for alignments on the reverse strand. I wasn't able to understand why (the pull request is always high, maybe by the number of mismatches). Could you look into this on your end? I've posted some short example sequences at
https://psu.box.com/s/fp2zwa90v1r92fzcchqykztcxyb77lbn that have ≈50 alignments from lastz default settings, ≈20 on the reverse strand.

(For 1, 2, and 3, I'm not looking for you to fix the pull request code, if that were what was needed. I'm just looking for verification that what the awk script produces is correct, or, if not, what correct should look like). 

(4) The CIGAR change will be easy, as the function that generates the string has an option for this distinction. One of the problems with CIGAR is the lack of a spec early on (if ever), and developers had differing interpretations about what was correct.

(5) I'm reticent to call this option --format=paf, because it's not *just* paf, It's paf specific to some particular downstream tool suite. So --format=paf_for_xxx or --format=paf:xxx would make more sense to me, where xxx is some suite of tools (or tool) that needs those two extra tags.

(5b) I also worry that as soon as I add this, other users will request other paf variants. These would best be served by users being allowed to list which tags they want, similar to how --format=general works. That's one of the reasons I feel like --format=general is a better solution. To me it seems the only shortcoming it has at present is that it doesn't provide all the fields you need.

**Comment by urbanslug** [comment]
It seems my PR wasn't as good as I thought it was and you found a number of problems :)

1)
The sequence length is off by one as you state.
The reason I added 1 to the sequence lengths is because it seemed to be less by 1 when I was writing the code (I was checking by piping `tail` output to `wc`) so I thought something weird was happening in a function upstream but I was not sure why. I assumed something interesting was happening with the string handling and added the comment.

After fixing different parts of the `paf.c` and looking again at it now I shouldn't be adding 1 to the sequence lengths.

2)
Yes, column 11 doesn't count the matches but I did in the CIGAR string. My test case must not have been exhaustive enough or I somehow just missed that. I can see https://github.com/urbanslug/lastz/blob/master/src/paf.c#L355 totally fails to add mismatches

3)
It could be that there are problems in my handling of the reverse strand.
I did have trouble with that but it worked for my test cases.

4)
The CIGAR string being produced does have the format required by downstream tools i.e. 1= rather than just =

5 a&b) As long as it follows PAF (the first 12 columns) the spec does leave it quite open to interpretation, right? I don't have particularly strong feelings about how to proceed.
I do however think having `paf` as an output format option would be nice.

**Comment by rsharris** [comment]
I've added a better test case at that same psu.box.com link. lime.fa query onto lemon.fa (lastz has query second, so lastz lemon.fa lime.fa). This is a few reads of length ≈300 mapped to a short genome. Divergence is less than 2% so minimap should have no trouble mapping these. (I haven't done that yet though). That will facilatate comparison between minimap output and lastz output.

**Comment by rsharris** [comment]
Comparing to minimap2 output (I don't have minimap installed), it looks like the "as" tag is supposed to be uppercase "AS". I can't find a spec for these optional tags. I thought they used to be in the SAM spec but I can't find them in there now.

Alignment positions can't be verified by this test set, because the two aligners give difference results. Most likely lastz is including "random tails" that minimap2 is smart enough to discard (though inspection of a few cases doesn't agree with that hypothesis).

**Comment by rsharris** [comment]
@urbanslug "It could be that there are problems in my handling of the reverse strand. I did have trouble with that but it worked for my test cases."

Devising good test cases is a good skill to have. ;) Experience has taught me that a lot of implementations fail on the reverse strand, including my own.

**Comment by urbanslug** [comment]
This might be the spec you are referring to with regards to "AS" https://samtools.github.io/hts-specs/SAMtags.pdf

**Comment by rsharris** [comment]
Yes!  Thanks!

In ancient times those were in the main SAM spec, so I went looking for them there. I see now that they were moved to this separate document 5 years ago (according to the tag history section of the tag doc). And a slower look at the main SAM spec reveals a hook pointing to this document.

**Comment by urbanslug** [comment]
I should probably add that I used the lowercase `as` because it's what the tool I was comparing it with (https://github.com/ekg/wfmash) uses.

**Comment by urbanslug** [comment]
It's perfectly understandable to look for a document on the internet (tangled mess of **web** pages) and not find it :)

**Comment by rsharris** [comment]
Regarding "as" vs "AS", IIRC the SAM spec says something about uppercase vs lowercase in tag names. I *think* uppercase is the ones defined in the spec, and lowercase is available for other tools to define as they see fit.

But it seems strange to have a lowercase tag with the same name and meaning as an uppercase tag defined in the spec.

Does wfmash give any rationale for why they use a lowercase tag?

**Comment by rsharris** [comment]
I realized, while looking at implementing this, that lastz does have a field corresponding to PAF column 11. I've edited my comments above to mention that, including the slightly simplified awk solution.

Also, I've posted a better test case for comparing lastz to minimap or minimap2. In the same box.psu directory as above, plum.fa (query) and sloe.fa (reference). The embedded homologies begin and end with ≈50 bp perfect matches and are flanked by ≈30 bp of no-matching segments (AC in the query, GT in the reference, or vice versa). This makes if highly likely that both aligners will find the same endpoints on both ends of the alignment.

**Comment by rsharris** [comment]
@ekg @urbanslug I have a private implementation of this, and scanty testing shows it agrees with minimap2 in most cases. (The differences are clearly due to differences in the alignment, not in the format). The CG tag format doesn't match minimap2, it matches what you have in your implementation. (Unless I have missed some option, minimap2 doesn't indicate mismatches in the CG tag)

I need a couple answers from you guys before I would pull my implementation into the main repo.

(1) I'm currently calling this --format=paf:garrison, since several of the details seem specific to (what I presume is) the Garrison Lab. A more generic name would be better. As I noted above, I don't think it makes sense to just call this --format=paf. Can you suggest something related to the tool suite this will fit with?

(2) My preference for the "AS" tag is to output it in upper case so as to be compliant with the spec. wfmash apparently writes it in lowercase. Is that a non-compliance bug or is there some reason for it? Do the downstream tools you intend to use this in *expect* lowercase or are the robust to case differences? (Perhaps I'm wrong about how case is used in SAME tag names?).

If you can let me know the answers before the weekend, I can incorporate this into the master branch.

**Comment by ekg** [comment]
Thanks @rsharris for picking this up and developing an implementation of it. I thought I'd give some history to our interest in directly producing minimap-style PAF format. We thought that a patch to lastz might make things easier for any potential users for the banal reason that it will make it more comfortable to use it interactively.

It's worth describing the history of our use of this particular PAF format.

I worked on variation graph models to represent collections of genome alignments. These are compatible with the model used by the Cactus whole genome alignment algorithm (which uses lastz), and in fact I have had a very long collaboration with Bendict Paten's group, including a postdoc that I completed late last year. Starting during my PhD, I have developed a method that focused solely on the graph induction problem: [seqwish](https://github.com/ekg/seqwish). This consumes (minimap2-style) PAF with CIGARs, a set of sequences that are related by the alignments, and emits a graph model that represents both in GFA format. This has since evolved into the core component of a pangenome graph building tool, [pggb](https://github.com/pangenome/pggb).

For scalability reasons, I first used minimap2 alignments. However, minimap2 wasn't fast enough for the problems we were giving it (e.g. 90 human haplotypes, whole genome), so I then developed [edyeet](https://github.com/ekg/edyeet) and [wfmash[(https://github.com/ekg/wfmash). These forked mashmap2 and made it produce PAF output that was compatible with minimap2's format, and thus the seqwish input. Here, @urbanslug is working to better understand the interfaces of lastz so that we can potentially use it to derive the base-level alignments for mashmap2 mappings, as we're doing in wfmash and edyeet. These both use a high-level adaptation of the wavefront algorithm [WFA](https://github.com/smarco/WFA).

I actually wasn't aware that there was another "PAF" or that it was a more generic format. When presented as part of minimap/2 there was no mention made of its history or any potential name collisions. That's caused some confusion here, but I think we've sorted it out.

> (1) I'm currently calling this --format=paf:garrison, since several of the details seem specific to (what I presume is) the Garrison Lab. A more generic name would be better. As I noted above, I don't think it makes sense to just call this --format=paf. Can you suggest something related to the tool suite this will fit with?

Based on its current use, I'd suspect that most bioinformaticians expect .paf files to be those equivalent to what minimap2 makes. Perhaps it would be least confusing if we don't identify it as paf:garrison... but rather relate it to minimap2? Could we call it --format=paf2? We specifically differ from default minimap2 PAF because we almost always add the CIGAR field. What do you think?

**Comment by rsharris** [comment]
@ekg Thanks, the history helps.

`Perhaps it would be least confusing if we don't identify it as paf:garrison... but rather relate it to minimap2? Could we call it --format=paf2? We specifically differ from default minimap2 PAF because we almost always add the CIGAR field. What do you think?`

I think paf:wfmash would be more appropriate. There are more differences from minimap2 that just the addition of the cigar. "minimap2 -X" outputs five tags absent here. And "minimap2 -c -X" drops one of those and outputs 4 or 5 others, including cg. And its cg tag is different -- it's the old style that doesn't distinguish match from mismatch. (I'm using 2.17-r941 which I think is the latest release). Using --format=paf:wfmash will work nicely if other specific paf variations are added to lastz in the future. The README would/should describe the specific tags included.

**Comment by ekg** [comment]
That's fine although it might cause confusion by being too specific. There might not be lots of users though. They're probably all reading this thread. 

For compatibility with seqwish the only strict requirements are the start coordinates and orientation (fields 1, 3, 5, 6, 8) and the CIGAR. Most tools aren't really using any of the special fields from minimap2 besides the CIGAR. And the alignment score field being upper or lower case isn't a big deal. Maybe it should be AC rather than ac, but it hasn't caused problems. 

There is a PAF processing tool, fpa, https://gitlab.inria.fr/pmarijon/fpa. You might try to pass the output through it for your validation.

**Comment by rsharris** [comment]
@ekg @urbanslug OK, I've committed the changes implementing --format=PAF:wfmash.

I haven't tagged it as a release, but I did give it a version number, 1.04.11. The repo now stands at version 1.04.12.

It is briefly described in the html README.lastz.html.

Try it out, let me know if there are any problems.

As far as github is concerned, I'm going to deny the pull request of course.

**Comment by rsharris** [comment]
@urbanslug, if your still looking at the code base with an eye toward adding other formats, these changes will show how to incorporate tab-delimited one-line-per-alignment formats.

I'm also writing this up here so that if some one else comes along wanting to implement that type of format, I can point them at this post.

This would all be much simpler and clearer in a OOP language. Instead, we have a bunch of #define'd or enum'd codes and several switch statements. Admittedly old-fashioned.

Internally it's handled almost identically to --format=general. I added type codes for the new fields in genpaf.h, and added a pre-canned list of fields as a string). The new fields/codes are then implemented in several switch statements in genpaf.c.

There's a table, genpafName, that gives CLI names to the fields. I *didn't* add these PAF-specific codes to that table, because they don't seem useful for direct access. However, I *did* add a new cigar format field to that table (and added corresponding type code stuff above).

In output.h and new output format code was added, fmtGenpafPafWfMash. Cases for this code were added to a ≈ dozen switch statments in output.c (these would correspond to a dozen class methods in OOP). All of these are either do-nothings or match the same functionality of the other pre-canned-field-list formats.

Finally, in lastz.c, code is added to allow the user to specify this format. And some additional code was added to make sure that the aligner will know that the output format requires "true" sequence lengths. (In some use cases, the internal sequence length is different than the real one; it's not a problem unless the output format needs the real length).

~~~~~

Formats that don't fit that paradigm are harder to add, mainly because it's difficult for someone coming into the code to understand all the nuances to compute some particular alignment stat from the alignment state. I think you did a pretty good job with what you had in the PR, but still there were some issues. More my fault for lack of adequate description than yours.

**Comment by urbanslug** [comment]
@rsharris it's okay to deny the PR as long as we get the alignment format in :).

I have no complaints. 
 - The implementation is concise, only reusing what's in `genPaf`.
 - ` --format=paf:wfmash` output works well on my tests so far—I also tested by aligning (syntenic) human ch11 and mouse chr17 thanks to @Flavia95.

I think the PR is okay to close unless @ekg has an objection.

**Comment by urbanslug** [comment]
Okay, I'll close the PR now.

**Pull request closed without merging**
